### ISSUE TITLE
Spawning FARP no fuel

### ISSUE THREAD

**Issue by Eule22TBone** [tobi-be/SpawnFarpScript#1]
Delivered:
1x Fuel/Ammo heavy (3000kg)
1x Repair heavy [(3000kg)

Issue:
FARP spwans without the capability to refuel, but it has fuel 3000/6000kg. Sling-Load object Fuel/Ammo remains standing directly next to the created FARP.

Hooked the Fuel/ammo again an transported it into the middle of the FARP -> F10/divers/mobileFarp/"Create FARP/Enhance FARP" -> no fix
![Digital Combat Simulator  Black Shark Screenshot 2022 01 04 - 21 51 36 100](https://user-images.githubusercontent.com/40805078/148125038-53d37415-5db6-471a-8ccf-0acb49c70d05.png)

**Comment by tobi-be** [comment]
Expected behaviour!
